import numpy as np
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
import scipy.sparse.linalg as sparse
import scipy.sparse._csr as csr
from tqdm import tqdm   
from numba import jit
from matplotlib.path import Path
from scipy.spatial.distance import cdist
from matplotlib.patches import PathPatch
from scipy.stats import linregress 
from scipy.sparse import lil_matrix